import { localeConfig, type Locale } from "@/lib/i18n";

export const communityCopy = {
  en: {
    eyebrow: "Q&A community",
    title: "Ask Reasonix setup and CLI questions",
    description:
      "Browse public questions, share a reproducible setup issue, and reply from your Reasonix site account. Keep provider API keys out of every post.",
    newQuestion: "New question",
    searchPlaceholder: "Search questions",
    searchButton: "Search",
    allLanguages: "All languages",
    defaultLanguage: "Current language",
    visible: "Visible",
    hidden: "Hidden",
    allStatuses: "All",
    loading: "Loading community questions...",
    emptyTitle: "No questions yet",
    emptyBody: "Start with an installation, version, API-key setup, or CLI error question.",
    replies: "replies",
    askedBy: "Asked by",
    databaseMissingTitle: "Community database is not configured",
    databaseMissingBody:
      "Apply the Supabase migration and set NEXT_PUBLIC_SUPABASE_URL plus SUPABASE_SERVICE_ROLE_KEY to enable posts.",
    signInHint: "Sign in with Clerk before posting or replying.",
    backToCommunity: "Back to community",
    questionTitle: "Question title",
    questionBody: "Question details",
    language: "Language",
    publish: "Publish question",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    hide: "Hide",
    restore: "Restore",
    reply: "Reply",
    replyPlaceholder: "Write a useful answer or troubleshooting step.",
    postReply: "Post reply",
    noReplies: "No replies yet.",
    notFoundTitle: "Question not found",
    notFoundBody: "The question may be hidden, deleted, or unavailable.",
    articleDiscussionTitle: "Discuss this article in the community",
    articleDiscussionBody:
      "Use the site Q&A board for follow-up questions instead of an external comment thread.",
    articleDiscussionCta: "Open community",
  },
  "zh-cn": {
    eyebrow: "问答社区",
    title: "发布 Reasonix 安装、配置和命令行问题",
    description:
      "公开浏览问题，用 Reasonix 站内账号发帖和回复。问题可以写复现命令、版本和报错，但不要发布任何 provider API Key。",
    newQuestion: "发布问题",
    searchPlaceholder: "搜索问题",
    searchButton: "搜索",
    allLanguages: "全部语言",
    defaultLanguage: "当前语言",
    visible: "公开",
    hidden: "已隐藏",
    allStatuses: "全部",
    loading: "正在加载社区问题...",
    emptyTitle: "还没有问题",
    emptyBody: "可以先从安装、版本、API Key 配置或 CLI 报错开始发问。",
    replies: "条回复",
    askedBy: "提问者",
    databaseMissingTitle: "社区数据库还没有配置",
    databaseMissingBody:
      "请先应用 Supabase migration，并设置 NEXT_PUBLIC_SUPABASE_URL 和 SUPABASE_SERVICE_ROLE_KEY。",
    signInHint: "发帖或回复前请先通过 Clerk 登录。",
    backToCommunity: "返回社区",
    questionTitle: "问题标题",
    questionBody: "问题详情",
    language: "语言",
    publish: "发布问题",
    save: "保存",
    cancel: "取消",
    edit: "编辑",
    delete: "删除",
    hide: "隐藏",
    restore: "恢复",
    reply: "回复",
    replyPlaceholder: "写下可执行的排查步骤或答案。",
    postReply: "发布回复",
    noReplies: "还没有回复。",
    notFoundTitle: "没有找到这个问题",
    notFoundBody: "这个问题可能已经被隐藏、删除，或当前不可访问。",
    articleDiscussionTitle: "到社区继续讨论这篇文章",
    articleDiscussionBody:
      "文章后续问题统一进入站内问答社区，不再依赖外部评论串。",
    articleDiscussionCta: "打开社区",
  },
  "zh-tw": {
    eyebrow: "問答社群",
    title: "發布 Reasonix 安裝、設定和命令列問題",
    description:
      "公開瀏覽問題，用 Reasonix 站內帳號發文和回覆。問題可以寫復現命令、版本和錯誤，但不要發布任何 provider API Key。",
    newQuestion: "發布問題",
    searchPlaceholder: "搜尋問題",
    searchButton: "搜尋",
    allLanguages: "全部語言",
    defaultLanguage: "目前語言",
    visible: "公開",
    hidden: "已隱藏",
    allStatuses: "全部",
    loading: "正在載入社群問題...",
    emptyTitle: "還沒有問題",
    emptyBody: "可以先從安裝、版本、API Key 設定或 CLI 錯誤開始發問。",
    replies: "則回覆",
    askedBy: "提問者",
    databaseMissingTitle: "社群資料庫尚未設定",
    databaseMissingBody:
      "請先套用 Supabase migration，並設定 NEXT_PUBLIC_SUPABASE_URL 和 SUPABASE_SERVICE_ROLE_KEY。",
    signInHint: "發文或回覆前請先透過 Clerk 登入。",
    backToCommunity: "返回社群",
    questionTitle: "問題標題",
    questionBody: "問題詳情",
    language: "語言",
    publish: "發布問題",
    save: "儲存",
    cancel: "取消",
    edit: "編輯",
    delete: "刪除",
    hide: "隱藏",
    restore: "恢復",
    reply: "回覆",
    replyPlaceholder: "寫下可執行的排查步驟或答案。",
    postReply: "發布回覆",
    noReplies: "還沒有回覆。",
    notFoundTitle: "找不到這個問題",
    notFoundBody: "這個問題可能已被隱藏、刪除，或目前無法存取。",
    articleDiscussionTitle: "到社群繼續討論這篇文章",
    articleDiscussionBody:
      "文章後續問題統一進入站內問答社群，不再依賴外部留言串。",
    articleDiscussionCta: "開啟社群",
  },
  ru: {
    eyebrow: "Q&A community",
    title: "Задавайте вопросы по Reasonix setup и CLI",
    description:
      "Читайте public questions, публикуйте setup issues и отвечайте из аккаунта сайта Reasonix. Не добавляйте provider API keys в posts.",
    newQuestion: "Новый вопрос",
    searchPlaceholder: "Искать вопросы",
    searchButton: "Искать",
    allLanguages: "Все языки",
    defaultLanguage: "Текущий язык",
    visible: "Visible",
    hidden: "Hidden",
    allStatuses: "All",
    loading: "Загрузка вопросов...",
    emptyTitle: "Пока нет вопросов",
    emptyBody: "Начните с installation, version, API-key setup или CLI error.",
    replies: "ответов",
    askedBy: "Автор",
    databaseMissingTitle: "Community database не настроена",
    databaseMissingBody:
      "Примените Supabase migration и задайте NEXT_PUBLIC_SUPABASE_URL плюс SUPABASE_SERVICE_ROLE_KEY.",
    signInHint: "Войдите через Clerk перед публикацией или ответом.",
    backToCommunity: "Назад к community",
    questionTitle: "Заголовок вопроса",
    questionBody: "Детали вопроса",
    language: "Язык",
    publish: "Опубликовать",
    save: "Сохранить",
    cancel: "Отмена",
    edit: "Edit",
    delete: "Delete",
    hide: "Hide",
    restore: "Restore",
    reply: "Ответ",
    replyPlaceholder: "Напишите полезный troubleshooting step или answer.",
    postReply: "Опубликовать ответ",
    noReplies: "Пока нет ответов.",
    notFoundTitle: "Вопрос не найден",
    notFoundBody: "Вопрос может быть hidden, deleted или unavailable.",
    articleDiscussionTitle: "Обсудите статью в community",
    articleDiscussionBody:
      "Для follow-up questions используйте site Q&A board вместо external comment thread.",
    articleDiscussionCta: "Открыть community",
  },
} satisfies Record<Locale, Record<string, string>>;

export function formatCommunityDate(locale: Locale, value: string) {
  return new Intl.DateTimeFormat(localeConfig[locale].htmlLang, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}
